### ISSUE TITLE
Unable to compile for newer versions due to incompatible dependencies 

### ISSUE THREAD

**Issue by mohamed-aiman** [laracasts/testingvue#3]
**package.json** before

```
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "axios": "^0.18",
        "bootstrap": "^4.1.0",
        "cross-env": "^5.1",
        "laravel-mix": "^4.0.7",
        "lodash": "^4.17.15",
        "mocha": "^6.2.0",
        "mocha-webpack": "^1.1.0",
        "popper.js": "^1.12",
        "resolve-url-loader": "^2.3.1",
        "sass": "^1.15.2",
        "sass-loader": "^7.1.0",
        "tailwindcss": "^1.0.4",
        "tailwindcss-plugins": "^0.2.0",
        "vue": "^2.5.17",
        "vue-template-compiler": "^2.6.10",
        "vue-test-utils": "^1.0.0-beta.11"
    }
}
```

```npm run test``` returns compile error

Error trace

 WEBPACK  Failed to compile with 1 error(s)

Error: Chunk.parents: Use ChunkGroup.getParents() instead
    at Chunk.get (/Users/mberneis/dev/nanofetch/node_modules/webpack/lib/Chunk.js:827:9)
    at /Users/mberneis/dev/nanofetch/node_modules/mocha-webpack/lib/webpack/util/sortChunks.js:24:15
    at Array.forEach (<anonymous>)
    at sortChunks (/Users/mberneis/dev/nanofetch/node_modules/mocha-webpack/lib/webpack/util/sortChunks.js:23:10)
    at getBuildStats (/Users/mberneis/dev/nanofetch/node_modules/mocha-webpack/lib/webpack/util/getBuildStats.js:28:47)
    at TestRunner.prepareMocha (/Users/mberneis/dev/nanofetch/node_modules/mocha-webpack/lib/runner/TestRunner.js:141:52)
    at /Users/mberneis/dev/nanofetch/node_modules/mocha-webpack/lib/runner/TestRunner.js:193:36
    at /Users/mberneis/dev/nanofetch/node_modules/mocha-webpack/lib/webpack/compiler/registerReadyCallback.js:26:7
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/mberneis/dev/nanofetch/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:63:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/mberneis/dev/nanofetch/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/mberneis/dev/nanofetch/node_modules/webpack/lib/Compiler.js:267:22
    at Compiler.emitRecords (/Users/mberneis/dev/nanofetch/node_modules/webpack/lib/Compiler.js:449:39)
    at /Users/mberneis/dev/nanofetch/node_modules/webpack/lib/Compiler.js:261:10
    at /Users/mberneis/dev/nanofetch/node_modules/webpack/lib/Compiler.js:435:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/mberneis/dev/nanofetch/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:20:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/mberneis/dev/nanofetch/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/mberneis/dev/nanofetch/node_modules/webpack/lib/Compiler.js:432:27
    at /Users/mberneis/dev/nanofetch/node_modules/neo-async/async.js:2813:7
    at done (/Users/mberneis/dev/nanofetch/node_modules/neo-async/async.js:3521:9)
    at MemoryFileSystem.writeFile (/Users/mberneis/dev/nanofetch/node_modules/memory-fs/lib/MemoryFileSystem.js:328:9)
    at writeOut (/Users/mberneis/dev/nanofetch/node_modules/webpack/lib/Compiler.js:415:30)
    at /Users/mberneis/dev/nanofetch/node_modules/webpack/lib/Compiler.js:426:7
    at objectIteratorWithKey (/Users/mberneis/dev/nanofetch/node_modules/neo-async/async.js:3508:9)
    at timesSync (/Users/mberneis/dev/nanofetch/node_modules/neo-async/async.js:2292:7)
    at Object.eachLimit (/Users/mberneis/dev/nanofetch/node_modules/neo-async/async.js:3463:5)
    at emitFiles (/Users/mberneis/dev/nanofetch/node_modules/webpack/lib/Compiler.js:321:13)
    at Immediate._onImmediate (/Users/mberneis/dev/nanofetch/node_modules/memory-fs/lib/MemoryFileSystem.js:288:4)
    at processImmediate (internal/timers.js:439:21)

**Comment by mohamed-aiman** [comment]
fixed this issue with following dependencies for ```"vue": "^2.5.17"```


```
        "vue-test-utils": "^1.0.0-beta.3",
        "expect": "^23.6.0",
        "jsdom": "^13.1.0",
        "jsdom-global": "^3.0.2",
        "mocha": "^5.2.0",
        "mocha-webpack": "^2.0.0-beta.0"
```

**Comment by dmlogic** [comment]
Similar problems October 2020. It does appear the techniques in this lesson are no longer valid. I was able to get the tests to run as expected by replacing mocha-webpack with mochapack as [described here](https://dev.to/tuandm/how-to-test-vue-components-with-laravel-mix-and-mocha-3kgc)
